apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fast-api-backend
  template:
    metadata:
      labels:
        app: fast-api-backend
    spec:
      containers:
        - name: fast-api-backend
          image: {{ .Values.fastapi.image.repository }}:{{ .Values.fastapi.image.tag }}
          ports:
            - containerPort: 80
