apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    app: {{ include "backend.name" . }}
    component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "backend.name" . }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}"
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_HOST
              value: {{ .Values.env.mongodbHost }}
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.mongodbUserSecret }}
                  key: {{ .Values.env.mongodbUserKey }}
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.mongodbPasswordSecret }}
                  key: {{ .Values.env.mongodbPasswordKey }}
