apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: 27017
      nodePort: {{ .Values.mongo.service.nodePort }}
  selector:
    app: mongo

