apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
  labels:
    app: backend
    component: backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: backend
    component: backend
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 80
      nodePort: {{ .Values.api.service.nodePort }}
