apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-fastapi-app.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }} # Default to 30001 if not specified
  selector:
    app: {{ include "my-fastapi-app.name" . }}

