apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-service
  labels:
    app: {{ include "backend.name" . }}
    component: backend
spec:
  selector:
    component: backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
