apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
spec:
  type: {{ .Values.fastapi.service.type }}
  ports:
    - port: {{ .Values.fastapi.service.port }}
      targetPort: 
      nodePort: {{ .Values.fastapi.service.nodePort }}
  selector:
    app: fast-api-backend


